drupal/values.yaml
Your values specify 'standard' as the storage mariadb should use.
'standard' is the name of the default storage class on GKE, but doesn't exist on Azure (there the default class is called 'default').
Wouldn't it be better to just not specify a storage class so the local default is used naturally?
The mariadb chart docs say:
```
##
```
=> Use default storage for mariadb

silta-cluster/values.yaml
The nfs provisioner has been unstable. Sometimes it uses a lot of memory (up to 1.8G) and seems to hold on to it forever, and it could also be that some of the issues are due to insufficient resources. Setting both requests and limits to the same value is recommended for a more consistent behavior, which in this case we really want.
Note that I applied this change to the currently deployed StatfulSet and things seem to work quite well.
=> SLT-245: Set resources for the nfs provisioner.

.circleci/config.yml, silta-cluster/requirements.lock, silta-cluster/requirements.yaml, silta-cluster/templates/splash.yaml, silta-cluster/values.yaml, simple/requirements.lock
NOTE: this PR includes an upgrade to the latest version of ambassador, which is now hosted in the stable Helm charts repository. I haven't tested it, I just wanted the chart repository deployment to work.
This is the first step towards moving away from using Github pages to host the charts repository. That is still functioning, but the charts are now additionally available from http://charts.wdr.io
=> SLT-258: Deploy chart repository to Google Cloud Storage

drupal/templates/drupal-volumes.yaml, drupal/tests/drupal_cron_test.yaml, drupal/tests/drupal_postinstall_test.yaml, drupal/tests/private_files_test.yaml, drupal/tests/reference_data_test.yaml, drupal/tests/volumes_test.yaml
Related PR: 
- https://github.com/wunderio/charts/pull/29 (obsolete with this PR)
- https://github.com/wunderio/drupal-project-k8s/pull/118
=> Only create explicit drupal PVs if using silta-shared storageClassName; Assume silta-shared storage in tests;

silta-cluster/templates/sshd-jumpserver.yaml, silta-cluster/values.yaml
This turned out to be a lot easier than I was expecting. See https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/ for the full documentation.
Once this is committed, we can simply restrict access by adding the IP of our VPN in the values file like this:
```
gitAuth:
allowedIps:
- 1.2.3.4/32
- 5.6.7.8/32
```
=> SLT-281: Enable limiting jumpserver access by ip.

silta-cluster/templates/sshd-jumpserver.yaml
Got errors while using `allowedIps` while using [this syntax](https://github.com/wunderio/charts/pull/38)
```
Error: YAML parse error on silta-cluster/templates/sshd-jumpserver.yaml: error converting YAML to JSON: yaml: line 11: did not find expected key
Error: UPGRADE FAILED: YAML parse error on silta-cluster/templates/sshd-jumpserver.yaml: error converting YAML to JSON: yaml: line 11: did not find expected key
```
this change fixes the issue.
=> Slight change in allowedIps usage

silta-cluster/values.yaml
We were using datawire repo before and it has `externalTrafficPolicy: Local` by default: https://github.com/datawire/ambassador/blob/3d630fb1c81ee1efa527ebd4d51df67093eb6e3e/docs/yaml/ambassador/ambassador-service.yaml#L8
but the stable allows changing that
https://github.com/helm/charts/blob/master/stable/ambassador/templates/service.yaml#L21
and defaults to ""
We need this to be `Local`
=> SLT-299: Setting ambassador externalTrafficPolicy to Local due to repo change

.circleci/config.yml, csi-rclone/templates/csi-controller-rclone.yaml, csi-rclone/templates/csi-nodeplugin-rclone.yaml, csi-rclone/tests/controller_test.yaml, csi-rclone/tests/node_plugin_test.yaml, csi-rclone/values.yaml, drupal/values.yaml, silta-cluster/templates/deployment-remover.yaml, silta-cluster/templates/splash.yaml, silta-cluster/templates/sshd-jumpserver.yaml, silta-cluster/values.yaml, simple/tests/deployment_test.yaml
Support services need to have dedicated resources to make sure that they are still functioning properly when the cluster is under load. This PR only makes the resources configurable, the parameters still need to be set when creating the silta-cluster helm release.
=> SLT-302: Make resources configurable for support services

drupal/templates/_domains.tpl, drupal/tests/drupal_ingress_test.yaml
The helm / golang template syntax is not always very readable, so here's the logic:
Use clusterName as is (12 characters)
If projectName is longer or equal to 30 characters, truncate to 27 characters + 3 character hash.
Calculate characters left until 64, taking two dots into account: 62  - clusterNameLength - projectNameLength
If environmentName is longer, truncate with a hash.
=> SLT-337: Shorten domain names but keep the longest possible readable name

frontend/Chart.yaml, frontend/values.yaml
HPA fails with `Warning   FailedGetResourceMetric   HorizontalPodAutoscaler   missing request for cpu` when resource requests are undefined.
=> Resource requests for frontend chart

drupal/requirements.lock, drupal/requirements.yaml
We don't have any projects using this yet, so even though the upgrade includes breaking changes this shouldn't cause any issue.
=> Update the memcached chart to version 3

drupal/Chart.yaml, drupal/templates/_helpers.tpl, drupal/templates/post-release.yaml, drupal/templates/reference-data-cron.yaml, drupal/tests/drupal_postinstall_test.yaml, drupal/tests/reference_data_test.yaml, drupal/values.yaml
This PR combines a few related changes:
- Only use gdpr-dump when taking reference data. Manual dumps are not sanitized as this has proved to be confusing and leads to potential data loss.
- Replace the configurable command for taking reference data with a dynamic command, so we can for example automatically include additional mounted volumes like private files.
- Automatically skip files larger than 5M. Some projects tend to have huge files which are problematic for deployments but not valuable for development.
- Make it possible to skip additional folders.
- Don't compress the tarball with the reference data files, it's slow and brings little or no improvement regarding file size.
- Display the content of the reference data folder, so it's visible when the file size becomes large.
These …
=> Improve reference data creation.

drupal/templates/drupal-deployment.yaml, frontend/templates/nginx.yaml
I realized that nginx wasn't getting restarted as needed. The cause was that the annotation for the checksum was in the wrong location.
=> Configmap checksums need to be on pods to be effective.

drupal/templates/drupal-cron.yaml
We might have issues again with missing newlines, concatenating job command with "else".
https://github.com/wunderio/charts/commit/18cfdb1a8a07407b39d9af830b03a74344116974#diff-2fe5aff2f692800af7abd3ec8ac19c5c
=> This should fix my earlier "fix" with cron command newlines

drupal/values.yaml
As discussed in Slack, this fixes a few projects that have issues with broken state after certain changes. The drawback is unnecessary cache rebuilds, but this might not be an issue.
=> Rebuild the Drupal cache on all deployments to handle various errors.

drupal/values.yaml
Config import might bring in new plugins that requires caches to be cleared. (Monitored regular WSOD after deployments).
Solution: Add cache clear after config import.
=> Fix missing plugin errors on deployments with new modules enabled.

drupal/templates/varnish-deployment.yaml, drupal/tests/varnish_test.yaml
Same checksum mechanism as we added in a few other places, just for varnish this time.
=> Add a checksum to the varnish pods to redeploy when the configMap changes.

simple/templates/configmap.yaml, simple/tests/configmap_test.yaml, simple/values.yaml
This allows having custom configuration (like location {}) in server context.
```
nginx:
serverExtraConfig: |
location = /randomlocation {
return 418; 
}
```
Frontend chart has this, but slightly different solution - the config block goes above basic auth.
https://github.com/wunderio/charts/blob/master/frontend/templates/configmap.yaml#L102
Here's a related PR for drupal-k8s, https://github.com/wunderio/drupal-project-k8s/pull/185
=> Simple chart: custom config block for nginx server context

csi-rclone/Chart.yaml, csi-rclone/templates/csi-controller-rclone.yaml, csi-rclone/templates/csi-nodeplugin-rclone.yaml, csi-rclone/values.yaml, silta-cluster/templates/high-priorityclass.yaml, silta-cluster/values.yaml
- Creates new PriorityClass "high-priority"
- Allows providing `priorityClassName` for csi-rclone chart
- Uses `high-priority` PriorityClass for csi-rclone and traefik
=> SLT-343 Set a priorityClass for silta-cluster resources

frontend/templates/_helpers.tpl, frontend/templates/services-deployment.yaml, frontend/tests/services-deployment_test.yaml, frontend/values.yaml
This is a straight port of the equivalent functionality from the Drupal chart.
=> SLT-423: Port usage of static IP to frontend chart.

frontend/templates/NOTES.txt, frontend/templates/configmap.yaml, frontend/tests/configmap_test.yaml, frontend/tests/services-deployment_test.yaml, frontend/values.yaml
This removes requirement of `exposedRoute` parameter for internal containers.
Commited to master branch of existing projects to have the `exposedRoute: '/'` -  
1. Searched for projects in our organisation that are using frontend chart and also all silta.yml files containing frontend values link. 
2. Added `exposedRoute: '/'` when applicable.
=> Removing default exposedRoute

drupal/values.yaml, frontend/values.yaml, silta-cluster/values.yaml
While memory limits are needed, especially for some memory-hungry applications that tend to reserve as much as they can, CPU limits have the effect of throttling CPU activity.
=> SLT-437: Remove CPU limits, they slow things down unnecessarily.

drupal/values.yaml
Builds were failing with the error below. This also happened while running `drush cr` manually:
```
$ drush cr
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 31:
The service "serializer" has a dependency on a non-existent service "book.manager".  
cache:rebuild [--cache-clear [CACHE-CLEAR]] [--no-cache-clear] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--xh-link XH-LINK] [--notify [NOTIFY]] [--druplicon] [--] <command>
```
When running `drush cim` manually, it showed there are configuration changes (on which the drush cr depended):
```
|            | …
```
=> drush cr can break build when there are configuration updates

frontend/templates/services-deployment.yaml, frontend/tests/services-deployment_test.yaml, frontend/values.yaml
We already have default values for minReplicas and maxReplicas, but not for the metrics. We need those to have a working autoscaler, and we don't want to replicate the cpu usage threshold of 80% everywhere.
=> Set default values for autoscaling, including metrics.

frontend/Chart.yaml, frontend/templates/services-cron.yaml, frontend/tests/services-cron_test.yaml, frontend/values.yaml
The default cron job configuration we had was based on the one in the Drupal chart, but we don't actually need most of the limitations (for example, Drupal cron fails if the previous cron run is not complete). Enabling more parallel jobs has shown to enable a considerable increase in throughput for some larger import tasks.
=> SLT-455: Support parallel cron jobs in the frontend chart

drupal/values.yaml
Since the default values are optimised for development environments, we shouldn't require having one replica running at all times (especially when we only use a single replica).
=> Remove the pod disruption budget for memcached, it prevents node upgrades

drupal/values.schema.json, drupal/values.yaml
Rather than the automated approach with https://github.com/wunderio/charts/pull/89, a manual approach would be more maintainable. Here's some basic validation, we can always add more details. Rather than going for complete coverage, I think it makes sense to focus on specific use cases. For example it doesn't make sense to validate things that would be caught by the kubernetes validation, such as putting a number of replicas that's negative.
=> SLT-438 schema validation for silta.yml

drupal/Chart.yaml, drupal/templates/shell-deployment.yaml, frontend/Chart.yaml, frontend/templates/services-deployment.yaml
Removes service environment variables in shell pod (ssh does not work due to 1000 env variable limitation).
https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables
=> enableServiceLinks for drupal and frontend containers

drupal/templates/drupal-cron.yaml, drupal/tests/drupal_cron_test.yaml, drupal/values.yaml
Cron jobs typically use more resources, requesting those prevents a too high load on the cluster.
=> SLT-459: Make cron job resources configurable

drupal/templates/backup-cron.yaml, drupal/templates/drupal-cron.yaml, drupal/templates/drupal-deployment.yaml, drupal/templates/post-release.yaml, drupal/templates/reference-data-cron.yaml, drupal/templates/varnish-deployment.yaml, frontend/templates/nginx.yaml, frontend/templates/services-cron.yaml, simple/templates/deployment.yaml
We don't know exactly why, but the number of service links and the environment variables cause cpu activity even when containers are idle.
=> Remove service links everywhere we can.

drupal/values.schema.json
Tested that it still triggers for production branches, and that it doesn't for non-production branches or for unspecified environments.
=> Don't enforce production checks if branch is unspecified.

drupal/values.yaml
I noticed the memcached requests less memory for container than it actually uses because of our setting.
=> Memcached memory request matched with the maxItemMemory setting.

.circleci/config.yml
With the introduction of the silta-release subchart, we added a requirement for having built dependencies when running `helm lint`, which required an update of the unittest plugin to work properly.
=> Fix validation

silta-cluster/Chart.lock, silta-cluster/Chart.yaml, silta-cluster/values.yaml, silta-downscaler/Chart.yaml, silta-downscaler/README.md, silta-downscaler/templates/downscaler-cron.yaml, silta-downscaler/templates/placeholder-upscaler.yaml, silta-downscaler/templates/rbac.yaml, silta-downscaler/values.yaml
This chart consists of a cron job and a deployment, both of which use https://github.com/wunderio/silta-downscaler, with a serviceAccount which has access to list and patch resources across the cluster.
=> Initial version of the silta downscaler.

drupal/templates/backup-cron.yaml, drupal/templates/reference-data-cron.yaml, drupal/values.yaml
These two cron jobs have a tendency to go over the requested resources and trigger alerts, even if they are running in the middle of the night. Having more cpu requested also guarantees a faster execution.
=> SLT-478: Set dedicated requests for the backup on referenceData cron jobs

drupal/Chart.lock, drupal/Chart.yaml
It looks like it will take some more time until https://github.com/elastic/helm-charts/pull/542 is merged, so we need to fork that chart to have a fix available for us in the meantime.
=> Temporarily use our fork of the elasticsearch chart.

drupal/Chart.yaml, drupal/files/settings.silta.php
This pr disables the usage of monolog in cli since it doesn't work well together with drush batch processing, but causes the process to fail when new threads are started and stdout is printed. Drush expects stdout to be valid json, but monolog interferes with that and causes json syntax errors.
=> Don't use monolog in cli

.circleci/config.yml, drupal/test.values.yaml, frontend/test.values.yaml, simple/test.values.yaml
A Helm dry run can catch quite a few errors, as the generated output is validated against the kubernetes API (even though nothing gets created). This provides us with another safety net when pushing out new releases.
The CircleCI script now looks for a file called `test.values.yaml` in each chart, this has many purposes:
- The existence of the file determines if a dry run should take place. For example we don't want to test charts that will only be used as subcharts.
- We can pass required attributes, such as the docker image required by services in the frontend chart.
- We can enable optional resources so that they are tested as well.
So far the drupal, frontend and simple charts are covered. It would be nice to include the silta-cluster chart as well, but since it creates some resources …
=> Add Helm dry run chart install to validation

frontend/values.schema.json
This doesn't do much, but it will at least warn when someone uses an unsupported top-level key. Validated with most of our frontend projects, no errors were thrown.
=> SLT-497: add basic configuration validation for the frontend chart.

silta-cluster/Chart.lock, silta-cluster/Chart.yaml
Issues:
- minio 2.5.14 does not exist in bitnami. replaced with 3.3 with no further testing.
- stable/traefik is not available anywhere else. traefik website links another chart instead, but it's based on traefik 2.0 (https://github.com/helm/charts/issues/17203; https://github.com/containous/traefik-helm-chart)
- stable/instana agent is not available anywhere else. Official website links to stable charts.
Separate stories create to tackle them in the future.
=> SLT-474: Stable repo deprecation for silta-cluster chart

drupal/Chart.yaml, drupal/templates/drupal-certificate.yaml, drupal/templates/drupal-ingress.yaml, drupal/tests/drupal_ingress_test.yaml
We have an interesting use case that requires using a wildcard as the domain prefix. This work, but the resource definition is only valid YAML if the hostnames are quoted.
=> Quote host names to support wildcards

drupal/values.yaml
We noticed this on a big project, but it should be fixed by default even if it's usually not a problem.
=> Give memcached some buffer or it will crash when the cache is full.

drupal/Chart.yaml, drupal/templates/shell-deployment.yaml, drupal/templates/shell-secret.yaml, drupal/tests/shell_deployment_test.yaml, drupal/values.yaml
Following things need to be released at the same time:
1. Chart update needs to be merged. Wait for chart to be tagged.
2. Tag a v0.1.x release for `drupal-shell` from master branch. Wait for image to be built.
3. Orb needs prefix change for shell image, so the shell image is rebuilt on the next deployment.
=> Drupal: Use external ssh key server for shell container

drupal/Chart.yaml, drupal/templates/drupal-ingress.yaml, drupal/templates/shell-deployment.yaml, frontend/Chart.yaml, frontend/templates/ingress.yaml, silta-cluster/Chart.yaml, silta-cluster/templates/deployment-remover-ingress.yaml, silta-cluster/templates/splash-ingress.yaml, silta-cluster/templates/ssh-key-server-ingress.yaml, silta-cluster/templates/ssh-key-server.yaml, silta-cluster/templates/sshd-jumpserver.yaml, silta-downscaler/templates/placeholder-upscaler.yaml, simple/Chart.yaml, simple/templates/ingress.yaml
The extensions/v1beta1 API is deprecated, and unsupported for Deployment resources starting with kubernetes 1.16. These resources are stateless, replacing them doesn't cause any issues.
=> SLT-502 replace deprecated apis

frontend/values.yaml
[nginx examples](http://nginx.org/en/docs/http/ngx_http_headers_module.html) do not quote the header keys, maybe we shouldn't do that either.
=> Do not quote the add_header example keys

drupal/Chart.yaml, drupal/files/settings.silta.php
This change makes Elasticsearch Helper configuration override in `settings.silta.php` compatible with both version Elasticsearch Helper 6.x and 7.x.
More information about Elasticsearch Helper configuration structure change in 7.x can be found here - https://github.com/wunderio/elasticsearch_helper/blob/8.x-7.x/UPGRADE.md#changes-in-configuration
Credits: Solution to combine config override for both version was suggested by @Jancis. 🎉
=> Support for Elasticsearch Helper 7.x is added

drupal/Chart.yaml, drupal/templates/_domains.tpl
Removed environmentName from being used as name for shell services, as it would be used to create multiple shell services with the same name in the case of deploying a drupal multisite.
=> Use release name to identify shell services

drupal/Chart.yaml, drupal/templates/_helpers.tpl
This PR stems from the discussion in this [Slack thread](https://wunder.slack.com/archives/C8UN6AG9W/p1589794939125800).
So basically I noticed that the `--ignore-table` options work in the `drupal.extract-reference-data` job but not in the `drupal.backup-command` job. After comparing the two, I found that it was the surrounding single quotes that broke it in the latter.
=> Fix the non-working table ignoring in db backup job

drupal/files/settings.silta.php
User story: https://wunder.atlassian.net/browse/SLT-505
Set the default cache backend to use memcache when a memcache server is available and when memcache cache backend is defined.
At the moment we only set the memcache host server settings, but it remains unused because it is not set as the backend cache for Drupal.
=> SLT-505: Set the cache backend to use memcache when memcache server is available

drupal/Chart.yaml, drupal/templates/_helpers.tpl, drupal/templates/backup-cron.yaml
Updates backup cronjob:
Test the DB .sql file by importing data into ephemeral mariadb container and bootstrapping drush against it.
=> SLT-508: Backup validation

drupal/files/settings.silta.php
This fixes the error that happens in projects using memcache in which it could not find the memcache backend class. For now we just check if the memcache libraries exists.
=> SLT-505: Re-enable and fix the error produced by the previous change

frontend/Chart.yaml, frontend/templates/services-deployment.yaml, frontend/values.yaml
Adds two custom jobs to be defined by the user:
Postinstall - executes after a new environment is made (common case is first deployment for a new branch);
Postupgrade - executes after each deployment.
Testing:
Create postinstall,postupgrade tasks for a service
Both of these tasks execute on the first deployment - check post-release pod logs.
Subsequent deployments only execute postrelease.
=> SLT-523: Execute custom command at the end of deployment

drupal/Chart.yaml, drupal/templates/drupal-configmap.yaml
PHP error log to `/proc/self/fd/2`
Removing php fpm child decorator from stdio error log (stdout)
=> PHP logging changes

drupal/Chart.yaml, drupal/templates/drupal-configmap.yaml
FPM config moved out of silta template, so fpm images can have have dedicated config. 
https://github.com/wunderio/drupal-php-fpm/commit/6df24f5dcf0b11035589c002ecf6c57acb81b3b8
https://github.com/wunderio/silta-images/commit/ab9930bd75e2b3343c4418e0955859f92cfd8e29
=> Drupal: Some FPM config moved to Docker container

silta-cluster/Chart.lock, silta-proxy/templates/proxy-deployment.yaml, silta-proxy/values.yaml
- Moving silta-proxy nodeSelectors and toleration conf to cluster specific yamls because cluster specific yaml configurations can't override nodeSelector (neither `{}` nor `null` worked)
- Use silta-images image repository for silta-proxy docker image
=> Silta-Cluster: silta-proxy nodeSelector and toleration changes

drupal/Chart.yaml, drupal/templates/drupal-backendconfig.yaml, drupal/templates/drupal-service.yaml, drupal/test.values.yaml, drupal/values.yaml
- Adds `cluster.type` setting (should be overriden by ci tool). Defaults to gke so existing deployments won't start to die.
- `backendConfig` only included on gke cluster
=> drupal-chart: cloud type setting; backendConfig only deployed to gke;

frontend/templates/certificate.yaml
Pointing exposeDomains certificate at the correct ingress for acme validations to succeed
=> exposeDomains certificate ingress fix

drupal/Chart.yaml, drupal/values.yaml
Memcache chart has been changed from Kubernetes stable to Bitnami (https://github.com/wunderio/drupal-project-k8s/commit/735d7e242e93484712fd0a5aef1d87e2bc5652e7) but the configurations to comply with Bitnami chart wasn't updated.
This pull request updates the memcached `maxMemorySize` from `memcached.maxItemMemory` to be passed as command argument. 
See https://github.com/wunderio/drupal-project-k8s/pull/316
=> Pass maxMemoryLimit and maxItemSize as command arguments to memcached. 

drupal/values.yaml
Changes proposed in this PR:
- reorder the default postupgrade commands in Drupal chart so that cache rebuild is the very first command being run
- apparently my IDE removed a bunch of whitespaces as well
Link to Slack discussion: https://wunder.slack.com/archives/C8UN6AG9W/p1616578842088100
=> Drupal chart: Fix failing postupgrade drush commands

drupal/values.yaml
This setting was implied in the varnish control key secrets template, but not visible to end users.
https://github.com/wunderio/charts/blob/master/drupal/templates/varnish-secret.yaml#L10-L14
This fixes it for people that are used to set a custom varnish key.
=> Document varnish key override

drupal/Chart.yaml, drupal/templates/_helpers.tpl, drupal/templates/drupal-configmap.yaml, drupal/templates/drupal-deployment.yaml, drupal/values.yaml
Replaces liveness probe with a combined check that both tries to prevent requests during the site installation process and checks the php-fpm process readiness before marking container as Ready.
This should prevent `"no live upstreams while connecting to upstream"` errors when the php-fpm process has not fully started up yet.
Plus, this PR removes the unused `.Values.php_ini.loglevel` and replaces with `.Values.nginx.loglevel`
Related PR: https://github.com/wunderio/drupal-project-k8s/pull/325
=> Unified probe for php-fpm readiness state

silta-cluster/templates/sshd-jumpserver.yaml, silta-cluster/values.yaml
When running on single node / vm setup if we bind the jumphost port to default ssh port we lose connectivity to the host node over ssh.
=> Make jumphost port configurable.

silta-cluster/Chart.yaml, silta-cluster/templates/sshd-jumpserver.yaml
When running e.g. Microk8s with Metallb on single host setups getting both sshd-jumpserver and Traefik ingress to share the host ip requires adding sharing key annotation to those services: https://github.com/metallb/metallb/blob/main/website/content/usage/_index.md#ip-address-sharing
=> Add annotations support to sshd-jumpserver.

drupal/Chart.yaml, drupal/templates/_helpers.tpl, drupal/values.yaml
In case the storage backend filesystem is already backed up there is no need to take extra backups of files.
https://github.com/wunderio/drupal-project-k8s/pull/323
=> Allow skipping files backup.

drupal/templates/drupal-configmap.yaml, frontend/Chart.yaml, frontend/templates/configmap.yaml, simple/Chart.yaml, simple/templates/configmap.yaml
Added suggested mitigations # 1 and # 4 from https://hexadix.com/slowloris-dos-attack-mitigation-nginx-web-server/
Other limits were already appropriate.
Tested and approved in https://github.com/wunderio/drupal-project-k8s/pull/327
=> Increase worker_connections and worker_rlimit_nofile.

drupal/templates/drupal-configmap.yaml, drupal/templates/varnish-configmap-vcl.yaml, drupal/tests/drupal_configmap_test.yaml, drupal/tests/shell_deployment_test.yaml, drupal/values.schema.json, drupal/values.yaml
- Allows having multivalue `nginx.realipfrom` list (map).
- X-Robots-Tag that returns `"noindex, nofollow, nosnippet, noarchive";` for all built-in domain responses (`branchname.project.clusterdomain`).
=> Drupal: Multivalue nginx.realipfrom; X-Robots-Tag

silta-cluster/Chart.yaml, silta-cluster/templates/sshd-jumpserver.yaml, silta-cluster/values.yaml
Allows to change replica count for jumpserver,ssh-keyserver.
Exposes storage options to allow for custom storage mounts.
=> rwx enabled mount for jumpserver

drupal/Chart.yaml, drupal/templates/_helpers.tpl, drupal/templates/drupal-configmap.yaml, drupal/templates/drupal-ingress.yaml, drupal/templates/drupal-service.yaml, drupal/values.yaml
- Exposes nginx session affinity option as .Values.nginx.sessionAffinity setting. False by default.
- tls hosts definition for ingress resources
- Disable tls for pxc cluster;
- Always create db if not exists
- Allows custom locations for retry404s.
- Disables gdprdump due to unavailable gdpr-dump extended mysqldump binary
- Deprecates old retry404s configuration schema (with failure message)
Old configuration syntax:
```
nginx:
retry404s: 5
```
New configuration syntax:
```
nginx:
retry404s:
delay: 5
paths:
- "^/sites/(.*)/files/(?:css|js)/(.*).(?:css|js)$"
- "^/sites/(.*)/files/(.*).(?:png|jpg)$"
```
=> Drupal: retry404s paths, tls hosts, nginx sticky sessions, pxc fixes

elasticsearch/templates/statefulset.yaml
Uses bash for shell in ES pods, as per 
https://github.com/elastic/helm-charts/commit/4e31e0cf3d025f9ce877ac52d218f49d72e26447
=> Use bash for elasticsearch

drupal/Chart.yaml, drupal/templates/solr-statefulset.yaml, drupal/values.yaml, elasticsearch/values.yaml, frontend/Chart.lock, frontend/Chart.yaml, frontend/templates/_overrides.tpl, frontend/tests/elasticsearch_test.yaml, frontend/values.yaml
- Reusing local elasticsearch chart fork for frontend chart & upgrading frontend es chart from 7.4 to 7.8;
- Upgrading default elasticsearch image from 7.4.1 to 7.16.1 (patched for log4j exploit) for frontend chart;
- Moving formatMsgNoLookups in frontend chart to library chart.
- Upgrading default elasticsearch image from 6.8.3 to 6.8.21 (patched for log4j exploit) for drupal chart;
- Temporary switching to forked solr 8 image with CVE-2021-44228 and CVE 2021-45046 [mitigation](https://github.com/wunderio/silta-images/commit/9060b7eb2e9431434a718311fe4e02a8b0f1c859).
=> Log4j jndi removal for ES; Frontend uses forked ES; ES image upgrades to patched versions

drupal/Chart.yaml, drupal/values.yaml, elasticsearch/values.yaml, frontend/Chart.yaml, frontend/values.yaml
- Drupal chart update default elasticsearch image to 6.8.22
- Frontend chart update default elasticsearch image to 7.16.2
- Forked elasticsearch chart update default elasticsearch image to 7.16.2
=> Updating default elasticsearch images to fix CVE-2021-45105

drupal/Chart.yaml, drupal/templates/drupal-ingress.yaml, drupal/templates/solr-statefulset.yaml, drupal/values.yaml, frontend/Chart.yaml, frontend/templates/ingress.yaml, simple/Chart.yaml, simple/templates/ingress.yaml
- Ingress pathType fix (drupal chart);
- Drupal: Solr 5 core path fix
- Drupal: Allow drush cr on an empty db in postinstall job.
=> Ingress pathType fix; Solr 5 path fix; drush cr on empty db

drupal/values.yaml
- Don't use capture, it's slower, and not needed
- Match only one dir level between sites/ and files/
- No need to match particular filenames, css|js dir is sufficient
- Filename matching had problems too:
- dot was not quoted
- .gz was not considered
- queries were not considered (?v=1.0.8)
- subdirs of js/ and css/ were not considered (fex .../js/optimised/...)
- So the reference pattern is now more universal and accurate at the same time
**How to test?**
Try this in regex101.com
=> Improve Nginx Retry404 RX

silta-cluster/Chart.yaml, silta-cluster/templates/_helpers.tpl, silta-cluster/templates/deployment-remover-ingress.yaml, silta-cluster/templates/splash-ingress.yaml, silta-cluster/templates/ssh-key-server-ingress.yaml, silta-cluster/templates/sshd-jumpserver.yaml, silta-downscaler/templates/_helpers.tpl, silta-downscaler/templates/placeholder-upscaler.yaml
- silta-cluster: Uses Ingress API v1 when kubernetes version is above 1.18. Includes required ingress changes. 
- silta-downscaler: `apiVersion` define variable name change
=> silta-cluster and silta-downscaler: Conditional apiVersion updates

silta-cluster/templates/sshd-jumpserver-cm.yaml, silta-cluster/templates/sshd-jumpserver.yaml, silta-cluster/values.yaml
- Sets externalTrafficPolicy to Local so remote IP's pass trough correctly
- Allows disabling key server (enabled by default for compatibility reasons)
```
gitAuth:
keyserver: 
enabled: false
```
- Allows defining static ssh keys (Related jumphost image commit https://github.com/wunderio/sshd-gitauth/commit/0c26869bcf8b239d12c242ccf1f788d47f65312c)
```
gitAuth:
authorizedKeys:
- "ssh-rsa ... user1@example.com"
- "ssh-rsa ... user2@example.com"
```
=> Allow defining static ssh keys;  Local externalTrafficPolicy

drupal/Chart.yaml, drupal/templates/drupal-ingress.yaml, drupal/test.values.yaml, drupal/tests/drupal_ingress_test.yaml, drupal/values.schema.json, frontend/Chart.yaml, frontend/test.values.yaml, frontend/tests/ingress_test.yaml, frontend/values.schema.json, simple/Chart.yaml, simple/tests/ingress_test.yaml, simple/values.schema.json
- Disallows old exposeDomains structure;
- Adds support for Azure's Application Gateway.
=> exposeDomains, AGW

drupal/Chart.lock, drupal/Chart.yaml, drupal/templates/_helpers.tpl, drupal/templates/drupal-configmap.yaml, drupal/templates/drupal-cron.yaml, drupal/templates/drupal-deployment.yaml, drupal/templates/drupal-service.yaml, elasticsearch/Chart.yaml, elasticsearch/templates/poddisruptionbudget.yaml, elasticsearch/templates/podsecuritypolicy.yaml, frontend/Chart.yaml, frontend/templates/configmap.yaml, frontend/templates/nginx.yaml, frontend/templates/service.yaml, simple/Chart.yaml, simple/templates/configmap.yaml, simple/templates/deployment.yaml, simple/templates/service.yaml
- [Drupal, Frontend, Simple] Changing nginx default port to 8080 due to nginx user being unable to open privileged ports
- Do not set user in nginx conf
- [Drupal] Cloud agnostic cronjob api version
- [Drupal] Workaround for php-fpm read only zz-custom.conf error message
- [Elasticsearch] Resource api version update
=> [Drupal; Frontend; Simple; Elasticsearch] nginx 8080, api version updates, bugfixes

drupal/Chart.yaml, drupal/templates/drupal-deployment.yaml, frontend/Chart.yaml, frontend/templates/services-deployment.yaml
Drupal, frontend charts:
- After deployment, do not reset pod count if site isn't idle
=> Conditional HPA

.github/workflows/pull-request.yml, .gitignore, silta-cluster/Chart.yaml, silta-cluster/templates/ingress.yaml, silta-cluster/templates/sshd-jumpserver.yaml, silta-cluster/test/values/minikube.yaml, silta-cluster/values.yaml, simple/Chart.yaml, simple/templates/configmap.yaml, simple/templates/deployment.yaml
simple chart (0.2.31):
- Set and allow custom UA for http probes (solves 401 for http readiness probes when pod ip range is not allowlisted) 
silta-cluster (0.2.33):
- Allow disabling ssl redirects for silta-cluster services ingress
- Allow overriding jumphost externalTrafficPolicy to enable ip sharing on MetalLB
- Silta chart compatibility tests on different kubernetes versions (via minikube) on Github Actions (weekly and for PR's)
=> Cluster tests

drupal/Chart.yaml, drupal/templates/_domains.tpl, drupal/values.schema.json, drupal/values.yaml
**Allows setting single subdomain.**
**Reasoning:**
_By default sites use branch.repo.cluster. If prefixes are enabled then there are even higher level of subdomains. This block using custom wildcard certificates._
**Features:**
-  Adds "singleSubdomain" flag to set "-" as a prefix, branch and repo separator.
- Set flag to "false" by default to not break any existing implementations
Tested on [drupal-project-k8s](https://github.com/wunderio/drupal-project-k8s/tree/single-subdomain). 
CI output [here](https://app.circleci.com/pipelines/github/wunderio/drupal-project-k8s/4195/workflows/5286f7c4-7113-4204-b182-b615ffdf8dc5/jobs/14298).
=> Single subdomain option

drupal/values.yaml, frontend/templates/backup-cron.yaml, frontend/values.yaml, silta-proxy/values.yaml
Silta docker container images are being migrated from [Google Container Registry](https://eu.gcr.io/silta-images/) to [Docker Hub](https://hub.docker.com/u/wunderio).
This PR changes base image location to the new image registry and adjusts some image names.
Please review adjusted image paths and make sure this PR only changes relevant configuration files.
This pull request was created with https://github.com/wunderio/internal-mass-updater.
=> Silta container base image migration to Docker Hub

drupal/Chart.yaml, drupal/values.yaml, frontend/Chart.yaml, frontend/values.yaml
- Uses updated mariadb subchart fork (https://github.com/wunderio/charts/pull/331 and https://github.com/wunderio/charts/pull/334)
- Disable mariadb enableServiceLinks in `drupal` and `frontend` charts by default
=> Use updated mariadb subchart fork, disable mariadb enableServiceLinks by default

csi-rclone/Chart.yaml, csi-rclone/templates/1.13-csi-nodeplugin-rclone.yaml, csi-rclone/templates/1.19-csi-nodeplugin-rclone.yaml
csi-rclone: maxUnavailable pods for quicker rclone nodeplugin updates
=> maxUnavailable pods for quicker rclone nodeplugin updates

.github/workflows/pull-request.yml
This PR is for testing 1.25 compatibility.
- adds helm unittests
- adds helm dry-run tests
=> Test charts on kubernetes 1.25

drupal/values.yaml
Set a baseline resource request for shell instead of using PHP resources as a default
=> Shell now has default values for resources

.github/workflows/pull-request.yml
- Fixes failing builds by increasing component readiness timeout in sandbox clusters
- Temporary patch for metallb image repo change until minikube has tagged `https://github.com/kubernetes/minikube/pull/16056`
- Tests on kubernetes 1.20 and 1.26
- Patch version updates
=> 1.26 tests, component setup timeout change, metallb image hotfix

silta-cluster/README.md
Ran into connection issue while testing Dataplane 2 with native Kubernetes Network policy objects. Turns out there is no mention about label requirement in silta-cluster chart docs.
=> namespace label requirement

drupal/templates/drupal-deployment.yaml
Proposed changes:
- Adds an identical preStop hook to the php container as we have in the nginx container
- Increase the sleep time in nginx and php preStop hooks in order to prevent errors as much as possible. This was tested with different settings, and for now 15s seemed good.
Related PR: https://github.com/wunderio/drupal-project-k8s/pull/624
=> SLT-846: 15s sleep in preStop hooks for php and nginx container

drupal/templates/drupal-configmap.yaml, drupal/templates/varnish-configmap-vcl.yaml
Currently we define certain headers and/or cache settings for images, but not for webp files.
This PR adds webp to the list of image extensions in both nginx and varnish configs.
Related PR: https://github.com/wunderio/drupal-project-k8s/pull/619
=> Added webp to the list of image extensions in nginx and varnish configs.

drupal/Chart.yaml, drupal/templates/varnish-service.yaml
This should fix the "Bad gateway" issue for downscaled sites. Helm does not replace spec.ports, just merges and since varnish service does not define targetPort, it just leaves the 8080 from downscaler.
=> drupal: specifies undefined targetPort so helm does not merge with downscaled 8080

drupal/templates/_helpers.tpl, frontend/templates/services-cron.yaml, frontend/templates/services-deployment.yaml
Current code generates incorrect template when value is of integer or float type. This adds additional types.
Before:
```
- name: FOO: 
value: "bar"
- name: BAR
"123"
```
After:
```
- name: FOO: 
value: "bar"
- name: BAR
value: "123"
```
=> Additional handling for other env value types

drupal/Chart.yaml, drupal/templates/drupal-configmap.yaml
Reverts https://github.com/wunderio/drupal-project-k8s/pull/644
Projects are having hard times with builds as base image is not pulled in docker builds unless the codebase has changed. Let's disable nginx vts module for few months until more or less all builds have pulled a more recent base image.
=> Drupal: disabling nginx vts stats page until base images images are updated

drupal/Chart.yaml, drupal/templates/_helpers.tpl, frontend/Chart.yaml, frontend/templates/services-cron.yaml, frontend/templates/services-deployment.yaml
handles invalid variable case, when value is `~`
=> invalid variable handling

drupal/Chart.yaml, drupal/templates/_domains.tpl, drupal/templates/_helpers.tpl, drupal/templates/backup-volume.yaml, drupal/templates/drupal-volumes.yaml, drupal/templates/shell-volume.yaml, drupal/tests/drupal_deployment_test.yaml, drupal/values.schema.json, drupal/values.yaml, frontend/Chart.yaml, frontend/templates/services-cron.yaml, frontend/values.yaml
Drupal chart (0.9.0)
- Added more tests for php env vars ([PR](https://github.com/wunderio/drupal-project-k8s/pull/650))
- SLT-883: Upgrade default MariaDB version to 10.6 ([PR](https://github.com/wunderio/drupal-project-k8s/pull/656))
- Added support for subdomain masking ([PR](https://github.com/wunderio/drupal-project-k8s/pull/653))
- Create backup and referenceData PersistentVolume only when using silta-shared storageclass ([PR](https://github.com/wunderio/drupal-project-k8s/pull/643))
Frontend chart (0.7.0)
- SLT-883: Upgrade default Maria DB version to 10.6 ([PR](https://github.com/wunderio/frontend-project-k8s/pull/99))
- Remove extra "echo" lines from cronjobs ([PR](https://github.com/wunderio/frontend-project-k8s/pull/97))
=> Release 2023-09-26

silta-cluster/Chart.lock, silta-cluster/Chart.yaml
Patched ingress-nginx chart against - [CVE-2023-5043](https://github.com/kubernetes/ingress-nginx/issues/10571), [CVE-2023-5044](https://github.com/kubernetes/ingress-nginx/issues/10572), [CVE-2022-4886](https://github.com/kubernetes/ingress-nginx/issues/10570)
=> Update ingress-nginx chart

.circleci/config.yml
Silta component adjustments to use v1.0 tags. There are no functional changes in this PR, 
image tags are pointed to the same images as before, but with v1.0 tags. 
From now on, Silta will aim to follow semantic versioning practices.
More information here: https://github.com/wunderio/silta/releases/tag/2023-10-03
Please review adjusted image tags and make sure this PR only changes relevant 
configuration files, feel free to make changes for components that have been left 
out from this PR.
This pull request was created with https://github.com/wunderio/internal-mass-updater.
=> Silta v1.0 components

drupal/templates/varnish-configmap-vcl.yaml
The regex currently in use is faulty and matches cases where the file extension appears inside the query string e.g. `example.com/path?foo=image.jpg`. Use the same improved pattern that we already have a few lines below in: https://github.com/wunderio/charts/blob/master/drupal/templates/varnish-configmap-vcl.yaml#L202
=> Fix varnish static file extension matching regex in vcl_backend_response

silta-cluster/Chart.yaml
silta-cluster chart version increase to start using the forked minio (6.0.5) subchart. Related PR: https://github.com/wunderio/charts/pull/404
=> use forked minio subchart

legacy_traefik/templates/deployment.yaml
This increases Traefik pod readiness probe initial delay from 10 to 45 seconds to mitigate the issue that Traefik starts to pass requests to pods in project namespaces before it is actually ready to do so.
Based on recent tests Traefik pods need around 36 seconds to start up in dev cluster.
The downside of this change if we just hard-code the delay value is that time for scaling-up traefik will increase (also in production) by 35 seconds and in case of rapid load spikes and little resource reserve that may not be ideal.
In ideal case we would have different value for development and production clusters.
=> SLT-965: Increase Traefik pod readiness probe initial delay

.github/workflows/pull-request.yml, drupal/Chart.yaml, drupal/templates/drupal-configmap.yaml, frontend/Chart.lock, frontend/Chart.yaml, frontend/templates/services-deployment.yaml, frontend/values.schema.json, frontend/values.yaml, legacy_traefik/templates/deployment.yaml, silta-cluster/Chart.yaml
Frontend chart (1.2.)
- ~[Add postgresql chart](https://github.com/wunderio/frontend-project-k8s/pull/107) (credit: @badrange)~ (removed due to bitnami common variable conflicts with forked versions.)
- [Fix for empty postinstall command](https://github.com/wunderio/frontend-project-k8s/pull/108)
Drupal chart (1.2.0)
- [Reenabling nginx vhost_traffic_status_module](https://github.com/wunderio/drupal-project-k8s/pull/677)
Silta-cluster (1.2.0)
- [Increase Traefik pod readiness probe initial delay](https://github.com/wunderio/charts/pull/408) (credit: @gatis)
Charts
- Chart integration tests with kubernetes 1.27.8 and 1.28.4 added, testing with 1.20.15 and 1.21.14 removed.
=> Release 2023-12-12

drupal/templates/drupal-cron.yaml, drupal/values.schema.json, drupal/values.yaml
**BackoffLimits should not be hardcoded and reduced to 1 attempt without option to change that.**
In specific sites there is need for increased backoff limit. Example:
Migrations are run every night against API that is not reliable and might not respond in time. In that case my only option is to   run them multiple times even if first attempt was successful.
Changes proposed:
- Set backoffLimit to 1 by default
- Allow setting backoffLimit per cron job
FYI: this is urgent as currently there is no other way to run migrations except for running them multiple times with no reason just because its not clear if they have finalised successfully. 
Tested: https://github.com/wunderio/drupal-project-k8s/tree/backoff
=> Feature: Configurable backoff limit.

.circleci/config.yml
This PR declares a resource_class for the custom job(s) in your CircleCI config.
Use the smallest possible option that works for your job, as the cost between small, medium and large doubles in size with each option. If your job fails due to lack of memory, try increasing the resource_class or optimizing your code if possible.
See the specs and cost for each option at https://circleci.com/product/features/resource-classes/#docker
The resource_class can be seen in CircleCI UI when clicking the job. You can also see how much CPU and RAM the job is using. See example screenshot:
CircleCI docs state:
> If a resource_class is not explicitly declared for a job, CircleCI will use a default resource class size. Defaults are subject to change. It is best practice to specify a resource class, …
=> Declare resource_class for custom job(s) in CircleCI config

legacy_traefik/templates/hpa.yaml, silta-cluster/Chart.yaml
This fixes issue where v2 api hpa configuration is copied directly into traefik hpa overrides. Allows having both original definition and the new one.
old:
```
autoscaling:
metrics:
- type: Resource
resource:
name: cpu
targetAverageUtilization: 80
- type: Resource
resource:
name: memory
targetAverageUtilization: 80
```
new:
```
autoscaling:
metrics:
- type: Resource
resource:
name: cpu
target:
type: Utilization
averageUtilization: 80
- type: Resource
resource:
name: memory
target:
type: Utilization
averageUtilization: 80
```
=> accept hpa v2 api configuration snippets in metrics

silta-cluster/Chart.yaml, silta-cluster/templates/nfs-server.yaml, silta-cluster/values.yaml
Adds rclone as optional storage backend for built in nfs server. NFS share is provisioned when `silta-nfs-shared` storageClass is defined for the storage.
Minimum setup instructions for GCS:
1. GCS bucket
2. ServiceAccount with access to bucket.
3. Deploy silta-cluster with additional values -  
```yaml
nfs-server:
enabled: true
persistence:    
rclone:
enabled: true
remotePath: gcs-bucket-name
backend_config: |
```
=> rclone as optional storage backend for nfs server

silta-cluster/Chart.lock, silta-cluster/Chart.yaml, silta-cluster/values.yaml
Allows replacing traefik with nginx (not enabled by default, but i'd say this should be default with silta 2.x)
Note: projects that redefine traefik annotations via `ingress.[ingress name].extraAnnotations` won't work anymore (i.e. custom rate limits). Chart defaults include both traefik and nginx annotations for default values.
Minimal configuration override for drop-in replacement:
```yaml
traefik:
enabled: false
nginx-traefik:
enabled: true
controller:
service:
loadBalancerIP: 1.1.1.1
config:
forwarded-for-header: "X-Forwarded-For"
proxy-real-ip-cidr: "1.1.1.1/1, 2.2.2.2/2"
```
Other settings available in chart defaults and ingress-nginx chart values.
=> nginx LB replacement for traefik

drupal/Chart.yaml, drupal/templates/drupal-configmap.yaml, drupal/templates/drupal-cron.yaml
Drupal chart:
- Fixes an error where cronjobs get set to `null`
=> Fixes querying non-initialized cronjobs

drupal/values.yaml, frontend/values.yaml
Updated the signal sciences waf container to use the latest container version. Updated cpu limits to avoid rare throttling situations that slows down the website.
=> WAF version update. CPU limit increase

csi-rclone/templates/1.13-csi-controller-rbac.yaml, csi-rclone/templates/1.13-csi-nodeplugin-rbac.yaml, csi-rclone/templates/1.19-csi-controller-rbac.yaml, csi-rclone/templates/1.19-csi-nodeplugin-rbac.yaml, csi-rclone/tests/1.13-controller_test.yaml, csi-rclone/tests/1.13-node_plugin_test.yaml, csi-rclone/tests/1.19-controller_test.yaml, csi-rclone/tests/1.19-node_plugin_test.yaml, csi-rclone/values.yaml
This PR
- adds support for service account annotations (so that IAM role annotations can be passed in)
=> Add annotation support for service accounts in csi-rclone chart

silta-cluster/Chart.lock, silta-cluster/Chart.yaml, silta-cluster/values.yaml
- ingress-nginx subchart update to latest
- Default configuration tweaks for nginx-traefik (ingress-nginx)
- sets ingressClass to default for nginx-traefik replacement (fixes cert-manager acme ingress issue)
- Zero downtime upgrade 
- Proxy connection defaults
- Error fixes (variables_hash; certificate.lua)
- custom rate limiter status codes (default value is a nondescriptive 503). This sets [arbitrary codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) as a replacement, will make it easier to identify which limit is hit. If ingress-nginx would send "[Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429)" header with status code 429, would use that instead.
- metrics endpoint example (might as well enable this by default)
=> ingress-nginx chart update; nginx-traefik ingressclass as default

csi-rclone/Chart.yaml, csi-rclone/templates/1.13-csi-controller-rbac.yaml, csi-rclone/templates/1.13-csi-nodeplugin-rbac.yaml, csi-rclone/templates/1.19-csi-controller-rbac.yaml, csi-rclone/templates/1.19-csi-nodeplugin-rbac.yaml, csi-rclone/tests/1.13-controller_test.yaml, csi-rclone/tests/1.13-node_plugin_test.yaml, csi-rclone/tests/1.19-controller_test.yaml, csi-rclone/tests/1.19-node_plugin_test.yaml, csi-rclone/values.yaml, drupal/Chart.yaml, drupal/templates/drupal-configmap.yaml, drupal/values.yaml, frontend/Chart.lock, frontend/Chart.yaml, frontend/templates/_helpers.tpl, frontend/templates/configmap.yaml, frontend/templates/services-deployment.yaml, frontend/test.values.yaml, frontend/tests/redis_test.yaml, frontend/values.schema.json, frontend/values.yaml, silta-cluster/Chart.lock, silta-cluster/Chart.yaml, silta-cluster/values.yaml, simple/Chart.yaml, simple/templates/configmap.yaml, simple/values.yaml
Frontend chart (1.8.0):
- Add lifecycle config with default 5s prestop for frontend services ([PR](https://github.com/wunderio/frontend-project-k8s/pull/120), credits Bernt)
- Add redis support ([PR](https://github.com/wunderio/frontend-project-k8s/pull/120), credits Mario)
- WAF version update. CPU limit increase ([PR](https://github.com/wunderio/charts/pull/431))
- Adds robots header for location scope; adds header for non-200 pages ([PR](https://github.com/wunderio/frontend-project-k8s/pull/126))
- Rate limit adjustment ([PR](https://github.com/wunderio/frontend-project-k8s/pull/125))
Drupal chart (1.9.0):
- WAF version update. CPU limit increase ([PR](https://github.com/wunderio/charts/pull/431))
- Adds robots header for location scope; adds header for non-200 pages …
=> Release 2024-05-21

silta-cluster/Chart.yaml, silta-cluster/values.yaml
Increases nginx LB proxy-buffer-size to 8k to solve nodejs auth issues
=> SLT-1044: proxy buffer size

silta-cluster/templates/sshd-jumpserver.yaml
Only change in the new version is this PR: https://github.com/wunderio/sshd-gitauth/pull/1
=> Update wunderio/sshd-gitauth image to v1.0 in sshd-jumpserver.yaml

.circleci/config.yml, .github/workflows/pull-request.yml, csi-rclone/tests/1.13-controller_test.yaml, csi-rclone/tests/1.13-node_plugin_test.yaml, csi-rclone/tests/1.19-controller_test.yaml, csi-rclone/tests/1.19-node_plugin_test.yaml
Proposed changes:
- Update helm unit tests to work with latest version of the helm-unittest plugin
- Upgrade the helm-unittest plugin in pull-request.yml
The drupal, frontend and simple chart tests are fixed in separate PRs and will eventually be merged to the release branch in this repo:
- https://github.com/wunderio/simple-project-k8s/pull/59
- https://github.com/wunderio/drupal-project-k8s/pull/711
- https://github.com/wunderio/frontend-project-k8s/pull/129
=> SLT-1026: Update helm unit tests to work with latest version of the helm-unittest plugin

csi-rclone/Chart.yaml, csi-rclone/README.md, csi-rclone/templates/1.13-csi-nodeplugin-rclone.yaml, csi-rclone/templates/1.19-csi-nodeplugin-rbac.yaml, csi-rclone/templates/1.19-csi-rclone-storageclass.yaml, csi-rclone/templates/1.20-csi-controller-rbac.yaml, csi-rclone/templates/1.20-csi-controller-rclone.yaml, csi-rclone/templates/1.20-csi-driver.yaml, csi-rclone/templates/1.20-csi-nodeplugin-rbac.yaml, csi-rclone/templates/1.20-csi-nodeplugin-rclone.yaml, csi-rclone/templates/1.20-csi-rclone-secret.yaml, csi-rclone/templates/1.20-csi-rclone-storageclass.yaml, csi-rclone/values.yaml
Related to and blocked by https://github.com/wunderio/csi-rclone/pull/54
Publishes `csi-rclone` chart version `1.0.0` when merged to master.
=> Template changes  for using csi-rclone provisioner

silta-cluster/Chart.lock, silta-cluster/Chart.yaml, silta-cluster/README.md, silta-cluster/docs/Upgrading-to-1.8.0.md, silta-cluster/templates/csi-rclone-upgrade-check.yaml, silta-cluster/templates/daemonset.yaml, silta-cluster/templates/silta-cluster-crd.yaml, silta-cluster/templates/sshd-jumpserver.yaml, silta-cluster/values.yaml
Blocked by https://github.com/wunderio/charts/pull/443
- Uses and requires updated csi-rclone
- Implements `releases.silta.wdr.io` crd to store release info (in the future) and allow conditional PV creation using `.Capabilities.APIVersions.Has "silta.wdr.io/v1"`. 
- Implements daemonset that adjusts shared memory allocation (`max_map_count`) on each node so that each deployment does not have to do it via privileged container. 
Note: there is an upgrade instruction which requires removal of `silta-storage` storageclass (`kubectl delete storageclass silta-shared`) before silta-cluster upgrade due to `provisioner` field being immutable (see `Upgrade path for older versions` in readme.md)
=> Silta cluster chart: Use new rclone provisioner, add daemonset for setting max_map_count

.github/workflows/pull-request.yml
Tests for 1.29 and 1.30. These were tested with latest, but now pinned in tests. Also, some patch versions were updated too.
=> Minikube tests for 1.29 and 1.30

.github/workflows/pull-request.yml, drupal/Chart.yaml, drupal/templates/_helpers.tpl, drupal/templates/backup-cron.yaml, drupal/templates/backup-volume.yaml, drupal/templates/drupal-volumes.yaml, drupal/templates/post-release.yaml, drupal/templates/reference-data-cron.yaml, drupal/templates/shell-deployment.yaml, drupal/templates/shell-volume.yaml, drupal/tests/drupal_cron_test.yaml, drupal/tests/drupal_postinstall_test.yaml, drupal/tests/private_files_test.yaml, drupal/tests/reference_data_test.yaml, drupal/values.schema.json, drupal/values.yaml, frontend/Chart.yaml, frontend/templates/_helpers.tpl, frontend/templates/backup-cron.yaml, frontend/templates/backup-volume.yaml, frontend/templates/services-cron.yaml, frontend/templates/services-deployment.yaml, frontend/templates/volumes.yaml, frontend/tests/volumes_test.yaml
Drupal chart (1.12.0)
- silta-shared PV adjustments for new csi-rclone provisioner ([PR 1](https://github.com/wunderio/drupal-project-k8s/pull/717), [PR 2](https://github.com/wunderio/drupal-project-k8s/pull/719), [PR 3](https://github.com/wunderio/drupal-project-k8s/pull/718))
- WNDR-281: Unpin patch version of mariadb, pin only major.minor versions ([PR](https://github.com/wunderio/drupal-project-k8s/pull/708))
- When extracting reference data files, ignoredFolders do not get deleted ([PR](https://github.com/wunderio/drupal-project-k8s/pull/716))
- job definitions for data sync via silta hub ([PR](https://github.com/wunderio/drupal-project-k8s/pull/712))
Frontend chart (1.11.0)
- silta-shared PV adjustments for new csi-rclone provisioner …
=> Release 2024-09-10

.circleci/config.yml, silta-cluster/docs/kyverno-policies/restrict-volume-types.yaml
- Skip sumologic namespace for volume restriction
- Use `helm template` instead of `helm install` to prevent cluster connection as we test charts on various versions in k8s repositories beforehand.
=> skip sumologic namespace for volume restriction

drupal/Chart.yaml, drupal/templates/backup-cron.yaml, drupal/values.schema.json, drupal/values.yaml
Drupal chart (1.15.0):
- Add nodeSelector support for backup jobs ([PR](https://github.com/wunderio/drupal-project-k8s/pull/726))
=> Release 2024-11-26

drupal/templates/clamav-configmap.yaml, drupal/templates/clamav-deployment.yaml, drupal/values.schema.json, drupal/values.yaml
This PR adds possibility to add clamd configuration to Clamav. The need is to change size limits for scanned files atm. If extra config is not defined, clamd conf file is not mounted from configmap preserving default config as-is in the container.
=> Drupal: Add possibility to change clamav config.

silta-cluster/docs/kyverno-policies/disallow-privilege-escalation.yaml, silta-cluster/docs/kyverno-policies/disallow-privileged-containers.yaml, silta-cluster/docs/kyverno-policies/restrict-adding-capabilities.yaml, silta-cluster/docs/kyverno-policies/restrict-seccomp.yaml, silta-cluster/docs/kyverno-policies/restrict-volume-types.yaml
Tested in production cluster:
- prevents `securityContext.allowPrivilegeEscalation`
- prevents `securityContext.capabilities` added other than NET_BIND_SERVICE or CAP_CHOWN 
\* some namespaces are added to exceptions
=> kyverno rule for disabling allowPrivilegeEscalation

silta-cluster/Chart.yaml, silta-cluster/templates/deployment-remover-sa.yaml
Set of policy rules tested with drupal, frontend and simple charts. This should be enough to remove deployments and avoid having wildcard access.
Removal on test cluster is only set up for drupal chart, tested with that, but it should work with frontend and simple charts too.
=> Narrowed down deployment remover rbac

frontend/Chart.yaml, frontend/templates/nginx.yaml, simple/Chart.yaml, simple/templates/deployment.yaml
- **Increase nginx shutdown delay from 5s to 15s on both simple and frontend charts**
- **Increased chart.yaml version**
=> SLT-1008: Increase nginx shutdown delay from 5s to 15s on both simple and frontend charts

silta-cluster/values.yaml
Related commit: https://github.com/wunderio/silta-nfs-subdir-external-provisioner/commit/d58bae39cbb2cafe95722d06bfe3bd16dd23bb92
~chart version is not updated, let's use the 1.9.0 from https://github.com/wunderio/charts/pull/458~
=> Updated image that fixes deleted pvc file removal

drupal/Chart.yaml, drupal/files/silta.services.yml, drupal/templates/_helpers.tpl, frontend/Chart.yaml, frontend/values.yaml
Drupal chart:
- SLT-1136: Drupal chart: Use JSON as the default formatter for application logs when handled by monolog ([PR](https://github.com/wunderio/drupal-project-k8s/pull/736), credits @k4lv15)
- Backup improvements ([PR](https://github.com/wunderio/drupal-project-k8s/pull/740))
- Update MariaDB values.yaml reference to our forked chart values ([PR](https://github.com/wunderio/charts/pull/468))
=> Release 2025-04-01

frontend/templates/services-cron.yaml, frontend/templates/services-deployment.yaml, frontend/values.schema.json, frontend/values.yaml
**Needed for n8n support.**
**Features:**
- Add securityContext configuration for services
- Update values.schema.json for validation
- Update templates to use new configuration options
- Add comprehensive examples in values.yaml
=> feat(frontend): add security context support

.circleci/config.yml, .github/workflows/pull-request.yml, drupal/Chart.lock, drupal/Chart.yaml, drupal/templates/NOTES.txt, drupal/templates/_helpers.tpl, drupal/templates/checks.yaml, drupal/templates/drupal-configmap.yaml, drupal/templates/smtp-secret.yaml, drupal/templates/varnish-configmap-vcl.yaml, drupal/test.values.yaml, drupal/tests/drupal_deployment_test.yaml, drupal/values.schema.json, drupal/values.yaml, frontend/Chart.lock, frontend/Chart.yaml, frontend/templates/NOTES.txt, frontend/templates/_helpers.tpl, frontend/templates/checks.yaml, frontend/templates/configmap.yaml, frontend/templates/varnish-configmap-vcl.yaml, frontend/test.values.yaml, frontend/values.schema.json, frontend/values.yaml
Drupal chart: https://github.com/wunderio/drupal-project-k8s/pull/741
Frontend chart: https://github.com/wunderio/frontend-project-k8s/pull/141
=> SLT-1103: Add mailpit support for drupal and frontend charts

.circleci/config.yml, .github/workflows/pull-request.yml, drupal/Chart.lock, drupal/Chart.yaml, drupal/templates/NOTES.txt, drupal/templates/_helpers.tpl, drupal/templates/checks.yaml, drupal/templates/drupal-configmap.yaml, drupal/templates/smtp-secret.yaml, drupal/templates/varnish-configmap-vcl.yaml, drupal/test.values.yaml, drupal/tests/drupal_deployment_test.yaml, drupal/values.schema.json, drupal/values.yaml, frontend/Chart.lock, frontend/Chart.yaml, frontend/templates/NOTES.txt, frontend/templates/_helpers.tpl, frontend/templates/checks.yaml, frontend/templates/configmap.yaml, frontend/templates/services-cron.yaml, frontend/templates/services-deployment.yaml, frontend/templates/varnish-configmap-vcl.yaml, frontend/test.values.yaml, frontend/values.schema.json, frontend/values.yaml, simple/Chart.yaml, simple/templates/configmap.yaml
Drupal chart:
- SLT-1185: mitigate 444 status code issue ([PR](https://github.com/wunderio/charts/pull/479))
- SLT-1103: Add mailpit support for drupal and frontend charts ([PR](https://github.com/wunderio/charts/pull/478), credits @k4lv15)
- SLT-1189: Add JA4 signature into nginx logs ([PR](https://github.com/wunderio/drupal-project-k8s/pull/744))
- Enable partial reference data import/export ([PR](https://github.com/wunderio/drupal-project-k8s/pull/742), credits @k4lv15)
- feat(frontend): add security context support ([PR](https://github.com/wunderio/charts/pull/477), credits @guncha25)
- SLT-1103: Add mailpit support for drupal and frontend charts ([PR](https://github.com/wunderio/charts/pull/478), credits @k4lv15)
- SLT-1189: Add JA4 signature into nginx logs …
=> Release 2025-05-06

drupal/Chart.yaml, drupal/templates/_helpers.tpl, drupal/values.schema.json, drupal/values.yaml, frontend/Chart.yaml, frontend/templates/services-deployment.yaml, frontend/values.schema.json, frontend/values.yaml
- #481 
Drupal chart:
- [Configurable Database Import Method](https://github.com/wunderio/drupal-project-k8s/pull/746/files)
=> Release 2025-05-13

drupal/Chart.yaml, drupal/templates/NOTES.txt, drupal/templates/_helpers.tpl, drupal/templates/shell-deployment.yaml, drupal/templates/shell-secret.yaml, drupal/tests/drupal_node_selector_test.yaml, drupal/tests/drupal_php_env_test.yaml, drupal/tests/shell_configmap_test.yaml, drupal/tests/shell_deployment_test.yaml, frontend/Chart.yaml, frontend/templates/NOTES.txt
Drupal chart:
- SLT-1037: Change default names in helm release notes ([PR](https://github.com/wunderio/charts/pull/487), credits Kalvis)
- Improve handling of the _installing file ([PR](https://github.com/wunderio/drupal-project-k8s/pull/747))
- Do not fail shell pod due to missing gitauth variables ([PR](https://github.com/wunderio/drupal-project-k8s/pull/756))
- SLT-1037: Change default names in helm release notes ([PR](https://github.com/wunderio/charts/pull/487), credits Kalvis)
=> Release 2025-06-17

drupal/templates/varnish-configmap-vcl.yaml, frontend/templates/varnish-configmap-vcl.yaml
- (drupal/varnish): Fix issue with Varnish varying cached static files by cookies
- (drupal/varnish, frontend/varnish): Fix URIBAN behavior, add support for URIBAN by regex
- Making a URIBAN request with a header like `x-url-invalidate-pattern: ^/sites/default/files/foo/bar\.pdf` will purge the cache from entries matching the pattern
- Making a URIBAN request with no such header will purge cache from entries which exactly match the Host header and the URL, just as before
- For the frontend chart, the BAN/URIBAN handling is moved before the allowed method checks (one would assume the previous placement made purging entirely non-functional)
=> Improve varnish config, add support for URIBAN by regex

.github/workflows/pull-request.yml, frontend/Chart.yaml, frontend/values.yaml, silta-cluster/Chart.lock, silta-cluster/Chart.yaml, silta-cluster/values.yaml
- Upgrade default nginx version to 1.28 ([PR](https://github.com/wunderio/frontend-project-k8s/pull/159))
- ingress-nginx update ([PR](https://github.com/wunderio/charts/pull/501))
=> Release 2025-09-09
