wunderio/charts

drupal/values.yaml
After deployment is a good idea to clear caches: I have had to do it manually to get the site to a good state after deployment.
=> Update values.yaml to clear drupal cache after deploy

docs/index.yaml
`silta-cluster` chart added to the index
=> Chart index update

silta-cluster/templates/sshd-jumpserver.yaml
Story: https://wunder.atlassian.net/browse/SLT-236
This is already deployed to `silta-1` cluster, works as expected.
=> SLT-236: PVC for SSH fingerprint keys

drupal/templates/_helpers.tpl, drupal/templates/drupal-deployment.yaml, drupal/templates/drupal-volumes.yaml, drupal/tests/drupal_cron_test.yaml, drupal/tests/drupal_postinstall_test.yaml, drupal/tests/private_files_test.yaml, drupal/tests/reference_data_test.yaml, drupal/tests/volumes_test.yaml, drupal/values.yaml
Related PR's / commits:
- https://github.com/wunderio/drupal-project-k8s/pull/115
- https://github.com/wunderio/drupal-project/commit/85a15b1d37a4b7604cf20c0ce3b69d64137614e4
=> SLT-203: Dynamic volume generation

.circleci/config.yml, silta-cluster/requirements.lock
The chart build process used to remove existing releases, which has caused some broken dependencies.
=> SLT-270: fix chart build

drupal/Chart.yaml, drupal/templates/_helpers.tpl, drupal/templates/drupal-configmap-nginx.yaml, drupal/templates/post-release.yaml, drupal/templates/reference-data-cron.yaml, drupal/tests/drupal_cron_test.yaml, drupal/tests/reference_data_test.yaml, drupal/tests/volumes_test.yaml, drupal/values.yaml
See https://github.com/wunderio/drupal-project-k8s/pull/116
=> SLT-268: Change the application root to /app

silta-cluster/Chart.yaml, silta-cluster/requirements.lock, silta-cluster/requirements.yaml, silta-cluster/values.yaml
We don't use the nfs provisioner, might as well remove it.
=> SLT-271: Remove the nfs provisioner from the silta-cluster chart.

drupal/values.yaml
See https://github.com/wunderio/drupal-project-k8s/pull/121
=> SLT-260: replace custom check-bootstrap command.

silta-cluster/requirements.lock, silta-cluster/requirements.yaml
- kube-state-metrics subchart downgrade; 
- ambassador and redis chart upgrade
=> silta-cluster dependency changes

silta-cluster/requirements.lock, silta-cluster/requirements.yaml, silta-cluster/values.yaml
Upgrade dependency to current version (tested on the test-cluster) and fixed broken reference.
=> Kube-state-metrics adjustments

silta-cluster/README.md
```
--limits=cpu=30m,memory=160Mi 
--requests=cpu=30m,memory=128Mi
```
=> SLT-317: Tiller resource limits

drupal/README.md, drupal/templates/NOTES.txt, drupal/templates/_domains.tpl, drupal/templates/drupal-certificate.yaml, drupal/templates/drupal-configmap-nginx.yaml, drupal/templates/drupal-ingress.yaml, drupal/templates/drupal-service.yaml, drupal/templates/varnish-configmap-vcl.yaml, drupal/tests/drupal_ingress_test.yaml, drupal/tests/drupal_service_test.yaml, drupal/values.yaml
see https://github.com/wunderio/drupal-project-k8s/pull/156
=> TLS support for drupal chart

frontend/templates/_helpers.tpl, frontend/tests/ingress_test.yaml
Changes from https://github.com/wunderio/charts/pull/61/files ported to frontend chart
=> SLT-337: Shorten domain names but keep the longest possible readable name.

drupal/templates/NOTES.txt, drupal/templates/drupal-certificate.yaml, drupal/templates/drupal-ingress.yaml, drupal/tests/drupal_ingress_test.yaml, drupal/values.yaml
This is needed to migrate sites using the domain module.
=> SLT-414: Add prefixes to the generated per-branch domains.

simple/templates/deployment.yaml, simple/values.yaml
This is a straight port of the same functionality in the Drupal chart.
=> Enable autoscaling for the simple chart.

.circleci/config.yml
Linting is working again, might as well re-enable it.
=> Re-enable linting

drupal/Chart.yaml, drupal/values.schema.json
merge this first: https://github.com/wunderio/silta-circleci/pull/82
=> Drupal: Allow branchName parameter in schema validation

drupal/templates/NOTES.txt
I guess this been asked a few times in various channels. This should help devs to grab a file from server...
=> Release notes example to download a file from Silta

drupal/Chart.yaml, drupal/templates/_helpers.tpl, drupal/templates/varnish-configmap-vcl.yaml, drupal/values.yaml
Features:
- Proxy ignore varnish
- Add values description for varnish
- Fix acl purge vcl settings
=> Varnish purger

simple/Chart.lock, simple/Chart.yaml, simple/templates/deployment.yaml, simple/values.yaml
Introduce networkpolicy as a subchart and make an exception to allow only ingress enter namespace boundary.
=> Includes networkpolicy exclusions

simple/Chart.yaml, simple/templates/configmap.yaml
Approved in https://github.com/wunderio/simple-project-k8s/pull/2
=> Enable redirects for simple chart.

frontend/Chart.yaml, frontend/templates/configmap.yaml, frontend/values.yaml
https://github.com/wunderio/frontend-project-k8s/pull/30#pullrequestreview-540644652
=> Security headers

drupal/Chart.yaml, drupal/templates/_helpers.tpl, drupal/values.yaml
Adds afterCommand variable which executes after php.postupgrade.command step.
=> SLT-544: Extend postrelease commands

drupal/Chart.yaml, drupal/templates/varnish-configmap-vcl.yaml, drupal/templates/varnish-deployment.yaml, drupal/values.yaml
Changes for drupal chart:
- Allow overriding varnish error 500 page html
- Using gcr hosted image for varnish
- Suppress mailhog logs
=> Release 20210129

drupal/Chart.yaml, drupal/values.yaml, frontend/Chart.yaml, frontend/templates/backendconfig.yaml, frontend/templates/service.yaml, simple/Chart.yaml, simple/templates/backendconfig.yaml, simple/templates/service.yaml
Adds missing backendconfig resources to frontend and simple charts; Also fixes default config typo for drupal backendConfig
=> Backendconfig for frontend and simple charts; Default backendconfig fix for drupal chart.

silta-cluster/Chart.yaml, silta-cluster/templates/k8s-controller-sidecars.yaml, silta-cluster/values.yaml
This won't affect deployments as it's config change only. The default config has not been overridden so far.
=> sidecar config typo fix

silta-cluster/README.md
Instructions on installing Calico, as a prerequisite.
=> Calico instructions

drupal/templates/varnish-configmap-vcl.yaml, drupal/values.yaml
https://github.com/wunderio/drupal-project-k8s/pull/308
=> Pipe varnish requests with content length bigger than 3Mb

simple/templates/configmap.yaml, simple/values.yaml
https://github.com/wunderio/simple-project-k8s/pull/4
=> Copy working security headers configuration from drupal chart.

drupal/Chart.yaml, drupal/templates/varnish-configmap-vcl.yaml, drupal/values.yaml
From this PR:
https://github.com/wunderio/drupal-project-k8s/pull/320
=> Make varnish backend config configurable

drupal/Chart.yaml, drupal/templates/_helpers.tpl, drupal/templates/drupal-configmap.yaml, drupal/templates/drupal-cron.yaml, drupal/values.schema.json, drupal/values.yaml
Applied changes from wunderio/drupal-project-k8s#324
=> Added support for configurable web root path.

drupal/templates/drupal-certificate.yaml, drupal/templates/drupal-ingress.yaml, drupal/values.yaml
Synced from https://github.com/wunderio/drupal-project-k8s/pull/322
=> Support for existing TLS secrets.

drupal/Chart.yaml, drupal/templates/drupal-configmap.yaml, drupal/values.yaml
Added connection limits per IP and gave bigger allowance to Nginx.
=> Rate limits

drupal/Chart.yaml, drupal/templates/drupal-configmap.yaml, drupal/values.yaml, frontend/Chart.yaml, frontend/templates/configmap.yaml, frontend/values.yaml, simple/Chart.yaml, simple/templates/configmap.yaml, simple/values.yaml
Allow changing X-Forwarded-For header to allow working with Cloudflare's special header
=> Allow changing real_ip_header

simple/Chart.yaml, simple/templates/certificate.yaml
Merging exposeDomainDefaults to the certificate iterator.
=> Merge exposeDomainDefaults to certificate domain

simple/Chart.yaml, simple/templates/_helpers.tpl, simple/templates/certificate.yaml, simple/templates/ingress.yaml
Simple chart cert-manager upgrade
=> Upgraded cert-manager support

drupal/Chart.yaml, drupal/templates/_helpers.tpl, drupal/templates/drupal-certificate.yaml, drupal/templates/drupal-ingress.yaml, frontend/Chart.yaml, frontend/templates/_helpers.tpl, frontend/templates/certificate.yaml, frontend/templates/ingress.yaml
Drupal and frontend chart cert-manager upgrades
=> cert-manager upgrades

frontend/Chart.yaml, frontend/templates/_helpers.tpl, frontend/templates/configmap.yaml
https://github.com/wunderio/frontend-project-k8s/pull/48
=> Add security headers under exposedRoutes.

drupal/Chart.yaml, drupal/templates/NOTES.txt, drupal/templates/_domains.tpl, drupal/templates/_helpers.tpl, drupal/templates/drupal-certificate.yaml, drupal/templates/drupal-configmap.yaml, drupal/templates/drupal-ingress.yaml, frontend/Chart.yaml, frontend/templates/NOTES.txt, frontend/templates/_domains.tpl, frontend/templates/certificate.yaml, frontend/templates/configmap.yaml, frontend/templates/ingress.yaml
Drupal, frontend:
Shortens full domain names to fit into certificate request SANs.
Drupal:
Lower compression level for faster validation.
=> Subdomain logic, db lower compression

drupal/Chart.yaml, drupal/values.yaml
Mitigating CVE-2021-44228 (https://github.com/advisories/GHSA-jfh8-c2jp-5v3q)
=> solr disable lookups

drupal/Chart.yaml, drupal/templates/_helpers.tpl
Hotfix: Do not delete db.sql file after compressing.
=> Dont delete input file

drupal/Chart.yaml, drupal/templates/shell-configmap.yaml, drupal/templates/shell-deployment.yaml, drupal/templates/shell-secret.yaml, drupal/tests/drupal_ingress_test.yaml, drupal/tests/shell_configmap_test.yaml, drupal/values.yaml, frontend/Chart.yaml, silta-cluster/Chart.yaml, silta-release/templates/_networkPolicy.tpl, silta-release/templates/network-policy.yaml, silta-release/tests/network_policy_test.yaml, simple/Chart.yaml
- Drupal: Allow defining static authorized keys for shell access, allow disabling key server; 
- Drupal, Frontend, Simple: kube-system namespace NetworkPolicy exclusion for incomming connections
=> static  authorized keys; kube-system networkpolicy allowlisting

silta-cluster/Chart.yaml, silta-downscaler/templates/_helpers.tpl, silta-downscaler/templates/placeholder-upscaler.yaml
Fixes template variable name so it does not overlap with parent chart
=> Template context fix

silta-cluster/Chart.yaml, silta-cluster/templates/_helpers.tpl, silta-cluster/templates/high-priorityclass.yaml
Change priorityclass API version depending on cluster.
=> Priorityclass API change

.circleci/config.yml, silta-cluster/Chart.lock, silta-cluster/Chart.yaml, silta-cluster/README.md, silta-cluster/values.yaml
Description for adding Filestore storage
=> Filestore support

drupal/Chart.yaml, drupal/templates/drupal-volumes.yaml
Add annotations to specify a location within a shared volume
=> storage annotations

silta-cluster/Chart.lock, silta-cluster/Chart.yaml, silta-cluster/templates/downscaler-upscaler.yaml, silta-cluster/templates/ingress.yaml, silta-cluster/values.yaml
- edit-in-place annotation for combined ingress
- traefik can be disabled
- other minor fixes
=> Ingress fixes

drupal/values.yaml
Sibling PR: https://github.com/wunderio/drupal-project-k8s/pull/469
Changes proposed:
- move one comment a few lines further down, since the comment specifically regards the drupal cron job
- add note about resource inheritance
=> Improved documentation about php cron jobs.

silta-cluster/Chart.yaml, silta-cluster/templates/_helpers.tpl
`semverCompare` seems to have some consistency issues, so we'll just check if api is present.
=> apiVersion conditionals adjustment

drupal/templates/drupal-certificate.yaml, drupal/templates/drupal-ingress.yaml
Use different secret name for custom certificates.
=> New name for custom cert secrets

drupal/Chart.yaml, drupal/values.yaml, frontend/Chart.yaml, frontend/README.md, frontend/templates/_helpers.tpl, frontend/values.schema.json, frontend/values.yaml
- Instana support (credit: **@mikaelkundert**)
Drupal chart:
- Redis resource assignment defaults moved to correct place
=> Feature release 20220526

drupal/Chart.yaml, drupal/templates/_helpers.tpl
Drupal chart (0.3.127): 
- Skip proxy for local connections
=> Skip proxy for local connections

drupal/Chart.yaml, drupal/templates/checks.yaml, drupal/values.schema.json
Drupal: Deployment values sanity check updates ([PR](https://github.com/wunderio/drupal-project-k8s/pull/510))
=> Drupal: Deployment values sanity check updates

silta-cluster/Chart.lock, silta-cluster/Chart.yaml, silta-cluster/values.yaml, silta-proxy/templates/proxy-deployment.yaml, silta-proxy/values.yaml
- probes for silta-proxy
- instana-agent subchart update (1.2.38 -> 1.2.43)
=> probes for silta-proxy; instana-agent subchart update;

drupal/Chart.lock, drupal/Chart.yaml, drupal/templates/_helpers.tpl, drupal/templates/drupal-ingress.yaml, drupal/templates/drupal-service.yaml, drupal/templates/varnish-deployment.yaml, drupal/templates/varnish-service.yaml
- Downscaler annotation fixes ([PR](https://github.com/wunderio/drupal-project-k8s/pull/514));
- Mailhog subchart upgrade ([PR](https://github.com/wunderio/drupal-project-k8s/pull/518));
- Varnish probes ([PR](https://github.com/wunderio/drupal-project-k8s/pull/519))
=> Downscaler annotation fixes; Mailhog subchart upgrade; Varnish probes

silta-cluster/Chart.yaml, silta-cluster/values.yaml, silta-downscaler/values.yaml
=> silta-downscaler: min age for dev deployments

drupal/Chart.yaml, drupal/templates/_helpers.tpl
Drupal chart: trigger silta entrypoint scripts if present.
=> Drupal: trigger silta entrypoint scripts if present.

frontend/templates/services-deployment.yaml
=> Add support for multiline postinstall and postupgrade commands

silta-cluster/values.yaml
Related PR: https://github.com/wunderio/silta-deployment-remover/pull/32
=> use refactored remover image

.circleci/config.yml, .github/workflows/pull-request.yml, silta-cluster/Chart.lock, silta-cluster/Chart.yaml, silta-cluster/README.md, silta-cluster/docs/ingress-controller.md, silta-cluster/templates/downscaler-rbac.yaml, silta-cluster/templates/ingress.yaml, silta-cluster/templates/splash-deployment.yaml, silta-cluster/values.yaml
Adds ingress-nginx (community version) and nginx-ingress (Ingress Inc. version) support
Note: merge this PR first: https://github.com/wunderio/silta-images/pull/88
=> nginx ingress support

silta-cluster/templates/downscaler-cron.yaml, silta-cluster/values.yaml
Adds missing PLACEHOLDER_PROXY_IMAGE
=> Adds missing PLACEHOLDER_PROXY_IMAGE

drupal/Chart.yaml, drupal/templates/drupal-configmap.yaml, drupal/templates/drupal-deployment.yaml, drupal/templates/varnish-configmap-vcl.yaml
Drupal chart (0.3.145):
- #365
- #368
=> Release 2023-05-11

drupal/Chart.yaml, drupal/templates/drupal-configmap.yaml, drupal/templates/drupal-deployment.yaml, drupal/templates/drupal-secret.yaml, drupal/values.schema.json, drupal/values.yaml, frontend/Chart.yaml, frontend/templates/configmap.yaml, frontend/templates/nginx.yaml, frontend/templates/secret.yaml, frontend/values.schema.json, frontend/values.yaml, simple/Chart.yaml, simple/templates/configmap.yaml, simple/templates/deployment.yaml, simple/templates/secret.yaml, simple/values.schema.json, simple/values.yaml
Drupal chart (0.4.0):
- https://github.com/wunderio/drupal-project-k8s/pull/629
Frontend chart (0.3.0):
- https://github.com/wunderio/frontend-project-k8s/pull/87
Simple chart (0.3.0):
- https://github.com/wunderio/simple-project-k8s/pull/41
=> Release 2023-06-08

drupal/Chart.yaml, drupal/values.yaml, frontend/Chart.yaml, frontend/values.yaml, simple/Chart.yaml, simple/values.yaml
Drupal chart (0.4.1):
- https://github.com/wunderio/drupal-project-k8s/pull/636
Frontend chart (0.3.1):
- https://github.com/wunderio/frontend-project-k8s/pull/90
Simple chart (0.3.1):
- https://github.com/wunderio/simple-project-k8s/pull/43
=> Release 2023-06-15

drupal/Chart.yaml, drupal/templates/_helpers.tpl, drupal/templates/drupal-configmap.yaml, drupal/templates/drupal-ingress.yaml, drupal/templates/drupal-volumes.yaml, drupal/tests/drupal_php_env_test.yaml, drupal/values.yaml, frontend/Chart.yaml, frontend/templates/_helpers.tpl, frontend/templates/services-cron.yaml, frontend/templates/services-deployment.yaml, frontend/templates/volumes.yaml
Drupal chart (0.5.0):
- https://github.com/wunderio/drupal-project-k8s/pull/632
- https://github.com/wunderio/drupal-project-k8s/pull/641
- https://github.com/wunderio/drupal-project-k8s/pull/635
- https://github.com/wunderio/drupal-project-k8s/pull/631
- https://github.com/wunderio/drupal-project-k8s/pull/628
- https://github.com/wunderio/drupal-project-k8s/pull/647
- https://github.com/wunderio/drupal-project-k8s/pull/637
Frontend chart (0.4.0):
- https://github.com/wunderio/frontend-project-k8s/pull/91
- https://github.com/wunderio/frontend-project-k8s/pull/89
=> Release 2023-08-03

drupal/Chart.yaml, drupal/templates/_helpers.tpl, frontend/Chart.yaml, frontend/templates/services-cron.yaml, frontend/templates/services-deployment.yaml
=> Boolean case

drupal/Chart.yaml, drupal/templates/drupal-configmap.yaml, drupal/templates/drupal-deployment.yaml, drupal/templates/varnish-configmap-vcl.yaml, drupal/values.yaml, frontend/Chart.yaml, frontend/templates/configmap.yaml, simple/Chart.yaml, simple/templates/ingress.yaml, simple/templates/service.yaml, simple/values.yaml
Drupal chart (0.7.0):
- https://github.com/wunderio/drupal-project-k8s/pull/644
Frontend chart (0.5.1):
- https://github.com/wunderio/frontend-project-k8s/pull/92
Simple chart (0.4.0):
- https://github.com/wunderio/simple-project-k8s/pull/44
=> Release 2023-08-17

silta-cluster/Chart.lock, silta-cluster/Chart.yaml, silta-cluster/README.md, silta-cluster/docs/Upgrading-to-0.2.43.md, silta-cluster/values.yaml
- pxc operator 1.9.1 -> 1.12.2
- ingress-nginx 4.6.0 -> 4.6.1
- nginx-ingress 0.17.0 -> 0.17.1
- instana-agent 1.2.56 -> 1.2.60
=> Pxc operator 1.9.1 to 1.12.2 + minor subhchart updates

.circleci/config.yml, silta-cluster/values.yaml
- Adjusted nginx defaults to avoid OOM's 
- Build fix (missing gcloud binary)
=> SLT-850: tuning nginx defaults to avoid OOMs during high request rate

.circleci/config.yml, drupal/Chart.lock, drupal/Chart.yaml, drupal/templates/_helpers.tpl, drupal/templates/drupal-ingress.yaml, drupal/templates/drupal-service.yaml, drupal/templates/shell-service.yaml, drupal/templates/solr-service.yaml, drupal/templates/varnish-service.yaml, drupal/tests/db_test.yaml, drupal/tests/drupal_ingress_test.yaml, drupal/values.yaml, frontend/Chart.yaml, frontend/templates/ingress.yaml, frontend/tests/ingress_test.yaml, silta-cluster/Chart.lock, silta-cluster/Chart.yaml, silta-cluster/README.md, silta-cluster/docs/Upgrading-to-0.2.43.md, silta-cluster/values.yaml, simple/Chart.yaml, simple/templates/ingress.yaml, simple/tests/ingress_test.yaml
Silta cluster chart (0.2.43):
- https://github.com/wunderio/charts/pull/373
- https://github.com/wunderio/charts/pull/386
Drupal chart (0.8.0):
- https://github.com/wunderio/drupal-project-k8s/pull/648
- https://github.com/wunderio/drupal-project-k8s/pull/654
- https://github.com/wunderio/drupal-project-k8s/pull/640
- https://github.com/wunderio/charts/pull/386
- https://github.com/wunderio/charts/pull/373
Frontend chart (0.6.0):
- https://github.com/wunderio/frontend-project-k8s/pull/96
Simple chart (0.5.0):
- https://github.com/wunderio/simple-project-k8s/pull/45
=> Release 2023-09-12

legacy_traefik/templates/hpa.yaml, silta-cluster/Chart.yaml
Conditional autoscaling api for 1.25+
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125
=> Traefik: conditional autoscaling api

drupal/Chart.yaml, drupal/files/settings.silta.d7.php, drupal/files/settings.silta.php, drupal/templates/_helpers.tpl
Allows to change database port for Drupal deployments
=> Expose DB port

legacy_traefik/templates/hpa.yaml, silta-cluster/Chart.yaml
Addition for https://github.com/wunderio/charts/pull/392
=> Traefik: conditional autoscaling api additions

drupal/Chart.yaml, frontend/Chart.yaml, frontend/templates/configmap.yaml, frontend/templates/services-deployment.yaml, legacy_traefik/templates/hpa.yaml
- Traefik legacy chart
- Traefik: conditional autoscaling api fixes
PR: https://github.com/wunderio/charts/pull/398
- frontend chart:
-  nginx configuration snippet templating 
PR: https://github.com/wunderio/frontend-project-k8s/pull/103
- Check if postinstall/postupgrade commands are defined
PR: https://github.com/wunderio/frontend-project-k8s/pull/104
=> Release 2023-11-09

frontend/Chart.lock, frontend/Chart.yaml, frontend/templates/NOTES.txt, frontend/templates/_helpers.tpl, frontend/templates/checks.yaml, frontend/templates/configmap.yaml, frontend/test.values.yaml, frontend/tests/elasticsearch_test.yaml, frontend/values.schema.json, frontend/values.yaml
- Mailhog service for frontend chart
=> Release 2023-11-16

drupal/Chart.yaml, drupal/templates/drupal-cron.yaml, drupal/values.schema.json, drupal/values.yaml
Drupal chart (1.3.0):
- https://github.com/wunderio/charts/pull/412
=> Release 2024-01-09

frontend/Chart.lock, frontend/Chart.yaml, frontend/templates/_domains.tpl, frontend/templates/_helpers.tpl, frontend/templates/configmap.yaml, frontend/templates/ingress.yaml, frontend/templates/nginx.yaml, frontend/templates/secret.yaml, frontend/templates/service.yaml, frontend/templates/services-deployment.yaml, frontend/templates/services-service.yaml, frontend/templates/varnish-configmap-vcl.yaml, frontend/templates/varnish-deployment.yaml, frontend/templates/varnish-secret.yaml, frontend/templates/varnish-service.yaml, frontend/templates/volumes.yaml, frontend/values.schema.json, frontend/values.yaml, legacy_traefik/templates/hpa.yaml, silta-cluster/Chart.yaml, silta-cluster/templates/nfs-server.yaml, silta-cluster/values.yaml
Frontend chart (1.4.0):
- https://github.com/wunderio/frontend-project-k8s/pull/109
- https://github.com/wunderio/frontend-project-k8s/pull/111
Silta cluster chart (1.3.0):
- https://github.com/wunderio/charts/pull/380/
Traefik chart:
- https://github.com/wunderio/charts/pull/416
=> Release 2024-02-06

frontend/Chart.yaml, frontend/templates/configmap.yaml, frontend/test.values.yaml
- SLT-997: Proxy auth header & JA3 logging ([PR](https://github.com/wunderio/frontend-project-k8s/pull/115))
=> Release 2024-03-05 frontend chart

drupal/Chart.yaml, drupal/templates/drupal-configmap.yaml, drupal/values.schema.json, drupal/values.yaml, silta-cluster/Chart.yaml, silta-cluster/README.md
Drupal chart (1.7.0):
- https://github.com/wunderio/drupal-project-k8s/pull/702
Silta cluster chart (1.4.1):
- https://github.com/wunderio/charts/pull/424
=> Release 2024-03-12

drupal/Chart.yaml, drupal/templates/drupal-configmap.yaml, drupal/templates/drupal-cron.yaml, drupal/tests/drupal_cron_test.yaml, drupal/values.schema.json, drupal/values.yaml, frontend/Chart.yaml, frontend/templates/configmap.yaml, frontend/values.yaml, simple/Chart.yaml, simple/templates/configmap.yaml
Simple chart (1.2.1):
- Mapping var, server block for proxy auth header ([PR](https://github.com/wunderio/simple-project-k8s/pull/54), credits Artis K)
Frontend chart (1.6.1):
- Mapping var, server block for proxy auth header ([PR](https://github.com/wunderio/frontend-project-k8s/pull/119), credits Artis K)
- SLT-921: Use latest silta-nginx image (nginx version 1.24) ([PR](https://github.com/wunderio/frontend-project-k8s/pull/118))
Drupal chart (1.8.0):
- Mapping var, server block for proxy auth header ([PR](https://github.com/wunderio/drupal-project-k8s/pull/704), credits Artis K)
- SLT-901: Added cronjob defaults and updated cronjob resource inheritance logic ([PR](https://github.com/wunderio/drupal-project-k8s/pull/662))
=> Release 2024-03-19

.github/workflows/pull-request.yml, frontend/Chart.lock, frontend/Chart.yaml, frontend/tests/mongodb_test.yaml, frontend/values.yaml
Frontend (1.7.0):
- https://github.com/wunderio/frontend-project-k8s/pull/116
- Related changes: [#124](https://github.com/wunderio/frontend-project-k8s/pull/124), [d18b9d8](https://github.com/wunderio/frontend-project-k8s/commit/d18b9d8223109150d96e23cd7928da1bc8ffdf8d), [4991e5e](https://github.com/wunderio/frontend-project-k8s/commit/4991e5efbc5aec8079d4c3a1f0c288f6a266436f)
=> Release 2024-04-09

drupal/Chart.yaml, drupal/files/settings.silta.php, drupal/templates/_helpers.tpl, drupal/templates/clamav-configmap.yaml, drupal/templates/clamav-deployment.yaml, drupal/templates/clamav-service.yaml, drupal/values.schema.json, drupal/values.yaml, frontend/Chart.yaml, frontend/templates/configmap.yaml, frontend/values.schema.json, frontend/values.yaml, silta-cluster/Chart.yaml, silta-cluster/values.yaml
Increase silta-downscaler values for main and dev environments ([PR](https://github.com/wunderio/charts/pull/438/files))
Drupal chart:
SLT-1034: ClamAV ([PR](https://github.com/wunderio/drupal-project-k8s/pull/713))
allow injecting custom snippet in service location; allow disabling dotfile blocking ([PR](https://github.com/wunderio/frontend-project-k8s/pull/130))
=> Release 2024-08-13

silta-cluster/README.md, silta-cluster/docs/kyverno-add-psa-labels-existing-ns.yaml, silta-cluster/docs/kyverno-policies/README.md, silta-cluster/docs/kyverno-policies/add-psa-labels.yaml, silta-cluster/docs/kyverno-policies/deny-privileged-profile.yaml, silta-cluster/docs/kyverno-policies/disallow-privileged-containers.yaml, silta-cluster/docs/kyverno-policies/restrict-volume-types.yaml
Kyverno setup instructions. 
Note: Do not provision example policies.
=> Kyverno setup instructions

csi-rclone/values.yaml, silta-cluster/Chart.yaml
Depends on https://github.com/wunderio/csi-rclone/pull/56
=> Bumping csi-rclone image version to 3.0.1

.circleci/config.yml, silta-cluster/docs/kyverno-policies/restrict-volume-types.yaml
- https://github.com/wunderio/charts/pull/449
=> Release 2024-10-01

drupal/Chart.yaml, drupal/templates/_helpers.tpl, drupal/templates/image-secrets.yaml, drupal/values.schema.json, drupal/values.yaml, frontend/Chart.yaml, frontend/templates/_helpers.tpl, frontend/templates/backup-cron.yaml, frontend/templates/image-secrets.yaml, frontend/templates/services-cron.yaml, frontend/templates/services-deployment.yaml, frontend/tests/backup-cron_test.yaml, frontend/tests/services-cron_test.yaml, frontend/tests/services-deployment_test.yaml, frontend/values.schema.json, frontend/values.yaml, silta-cluster/docs/Upgrading-to-1.8.0.md, simple/Chart.yaml, simple/templates/_helpers.tpl, simple/templates/deployment.yaml, simple/templates/image-secrets.yaml, simple/values.schema.json, simple/values.yaml
Drupal chart (1.13.0):
- Add support for custom imagePullSecret ([PR](https://github.com/wunderio/drupal-project-k8s/pull/723))
Frontend chart (1.12.0):
- Add support for custom imagePullSecret ([PR](https://github.com/wunderio/frontend-project-k8s/pull/135))
Simple chart (1.5.0):
- Add support for custom imagePullSecret ([PR](https://github.com/wunderio/simple-project-k8s/pull/61))
- Docs: Upgrading to 1.8.0 will require pod restarts ([PR](https://github.com/wunderio/charts/pull/451))
=> Release 2024-10-16

drupal/Chart.yaml, drupal/templates/drupal-cron.yaml
Drupal chart (1.14.0):
- https://github.com/wunderio/drupal-project-k8s/pull/724
=> Release 2024-11-19

drupal/Chart.yaml, drupal/templates/clamav-configmap.yaml, drupal/templates/clamav-deployment.yaml, drupal/values.schema.json, drupal/values.yaml
=> Release 2025-01-15

.github/workflows/pull-request.yml
- Helm v3.16.3
- Minikube tests with kubernetes 1.31
=> Helm v3.16.3, minikube tests with kubernetes 1.31

silta-cluster/Chart.yaml, silta-cluster/values.yaml
- https://github.com/wunderio/charts/pull/459
=> Release 2025-01-28

drupal/Chart.yaml, drupal/templates/serviceaccount.yaml
Drupal chart:
- Fix for SA automount ([PR](https://github.com/wunderio/drupal-project-k8s/pull/735))
=> Release 2025-02-18

forked/codecentric/mailhog-5.1.0/mailhog/.bumpversion.cfg, forked/codecentric/mailhog-5.1.0/mailhog/.helmignore, forked/codecentric/mailhog-5.1.0/mailhog/Chart.yaml, forked/codecentric/mailhog-5.1.0/mailhog/README.md, forked/codecentric/mailhog-5.1.0/mailhog/ci/ingress-values.yaml, forked/codecentric/mailhog-5.1.0/mailhog/templates/NOTES.txt, forked/codecentric/mailhog-5.1.0/mailhog/templates/_helpers.tpl, forked/codecentric/mailhog-5.1.0/mailhog/templates/auth-secret.yaml, forked/codecentric/mailhog-5.1.0/mailhog/templates/deployment.yaml, forked/codecentric/mailhog-5.1.0/mailhog/templates/ingress.yaml, forked/codecentric/mailhog-5.1.0/mailhog/templates/service.yaml, forked/codecentric/mailhog-5.1.0/mailhog/templates/serviceaccount.yaml, forked/codecentric/mailhog-5.1.0/mailhog/templates/smtp-secret.yaml, forked/codecentric/mailhog-5.1.0/mailhog/values.yaml
- Allows enableServiceLinks customization
- Disables service links by default
=> Allow mailhog enableServiceLinks customization

drupal/Chart.lock, drupal/Chart.yaml, drupal/values.yaml, frontend/Chart.lock, frontend/Chart.yaml, frontend/templates/nginx.yaml, frontend/values.yaml, silta-cluster/Chart.yaml, silta-cluster/docs/kyverno-policies/disallow-privilege-escalation.yaml, silta-cluster/docs/kyverno-policies/disallow-privileged-containers.yaml, silta-cluster/docs/kyverno-policies/restrict-adding-capabilities.yaml, silta-cluster/docs/kyverno-policies/restrict-volume-types.yaml
Drupal chart:
- Use mailhog fork and disable servicelinks ([PR](https://github.com/wunderio/drupal-project-k8s/pull/739))
- SLT-1164: Make sure gdprDump generates unique usernames in user_field_data ([PR](https://github.com/wunderio/drupal-project-k8s/pull/737), credits @k4lv15)
- Use mailhog fork and disable servicelinks ([PR](https://github.com/wunderio/frontend-project-k8s/pull/140))
- extraConfig mount fix ([PR](https://github.com/wunderio/frontend-project-k8s/pull/139))
- Lagoon PSP exclusions ([PR](https://github.com/wunderio/charts/pull/471))
=> Release 2025-03-18

frontend/Chart.yaml, frontend/templates/services-deployment.yaml, frontend/values.schema.json, frontend/values.yaml
Frontend chart PR: https://github.com/wunderio/frontend-project-k8s/pull/145
=> OPS-441: Added security context objects

.circleci/config.yml, drupal/Chart.yaml, drupal/templates/_domains.tpl, drupal/templates/backup-cron.yaml, drupal/templates/drupal-cron.yaml, drupal/templates/drupal-deployment.yaml, drupal/templates/shell-deployment.yaml, drupal/tests/drupal_affinity_test.yaml, drupal/tests/drupal_node_selector_test.yaml, drupal/tests/drupal_tolerations_test.yaml, drupal/values.schema.json, drupal/values.yaml, frontend/Chart.yaml, frontend/templates/services-cron.yaml, frontend/templates/services-deployment.yaml, frontend/tests/services-cron_test.yaml, frontend/values.schema.json, frontend/values.yaml
Drupal chart:
- SLT-911: Set domain masking to "none" by default ([PR](https://github.com/wunderio/drupal-project-k8s/pull/757))
- Custom affinities and tolerations ([PR](https://github.com/wunderio/drupal-project-k8s/pull/758))
- securityContext override for service cronjobs ([PR](https://github.com/wunderio/frontend-project-k8s/pull/151))
- Custom affinities and tolerations ([PR](https://github.com/wunderio/frontend-project-k8s/pull/152/))
=> Release 2025-08-05

drupal/Chart.yaml, drupal/templates/checks.yaml, drupal/templates/drupal-configmap.yaml, drupal/templates/varnish-configmap-vcl.yaml, drupal/tests/drupal_ingress_test.yaml, frontend/Chart.yaml, frontend/templates/checks.yaml, frontend/templates/varnish-configmap-vcl.yaml, frontend/tests/ingress_test.yaml, simple/Chart.yaml, simple/templates/checks.yaml, simple/tests/ingress_test.yaml
Drupal chart:
- Connection limit annotation validation ([PR](https://github.com/wunderio/drupal-project-k8s/pull/764))
- Duplicate configuration block removal ([PR](https://github.com/wunderio/drupal-project-k8s/pull/763))
- Improve varnish config, add support for URIBAN by regex ([PR](https://github.com/wunderio/charts/pull/495), credits @MarttiR)
- Connection limit annotation validation ([PR](https://github.com/wunderio/frontend-project-k8s/pull/157))
- Improve varnish config, add support for URIBAN by regex ([PR](https://github.com/wunderio/charts/pull/495), credits @MarttiR)
Simple chart:
- Connection limit annotation validation ([PR](https://github.com/wunderio/simple-project-k8s/pull/65))
=> Release 2025-08-26

.github/workflows/pull-request.yml, silta-cluster/Chart.lock, silta-cluster/Chart.yaml, silta-cluster/values.yaml
ingress-nginx chart upgrade to 4.13.2
=> silta-cluster: ingress-nginx update
